site_name: Documentación del Proyecto
theme:
  name: material

nav:
  - "Manual de Usuario": "docs_src/Manual_de_Usuario.md"
  - "Guía de Referencia": "docs_src/Guia_de_Referencia.md"
  - "Guía de Instalación": "docs_src/Guia_de_Instalacion.md"

markdown_extensions:
  - toc:
      permalink: true

extra:
  pdfs:
    - "docs_src/Manual_de_Usuario.pdf"
    - "docs_src/Guia_de_Referencia.pdf"
    - "docs_src/Guia_de_Instalacion.pdf"
