site_name: Documentación del Proyecto
theme:
  name: readthedocs

nav:
  - Manual de Usuario: Manual_de_Usuario.md
  - Guía de Referencia: Guia_de_Referencia.md
  - Guía de Instalación: Guia_de_Instalacion.md

plugins:
  - search
  - with-pdf:
      output_path: "site/pdf"
      separate_pdfs: true

docs_dir: docs_src
